/**
 * Keeps docker/compose.generated.yaml + node env markers in docker/compose.yaml
 * aligned with configs/app.blueprint.json (via npm run app:scaffold).
 */
import * as fs from "node:fs/promises";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

import type { SaaSAppBlueprint } from "./app-blueprint-config.js";

const _factoryDir = path.dirname(fileURLToPath(import.meta.url));
export const DOCKER_DIR = path.join(_factoryDir, "..", "docker");
export const COMPOSE_MAIN = path.join(DOCKER_DIR, "compose.yaml");
export const COMPOSE_GENERATED = path.join(DOCKER_DIR, "compose.generated.yaml");

/** Inside `node.environment` mapping (6 spaces) */
const NODE_ENV_START = "      # BLUEPRINT_NODE_ENV_START";
const NODE_ENV_END = "      # BLUEPRINT_NODE_ENV_END";

export function shouldEmitDockerInfra(bp: SaaSAppBlueprint): boolean {
  return (
    bp.tooling.containers === "docker-compose-dev" || bp.tooling.containers === "docker-compose-prod-sketch"
  );
}

function postgresVolumeName(slug: string): string {
  return `pgdata_${slug.replace(/[^a-zA-Z0-9_]/g, "_")}`;
}

/** Compose fragment merged via `include` from docker/compose.yaml */
export function dockerComposeGeneratedContents(bp: SaaSAppBlueprint, slug: string): string {
  const header =
    `# Generated by npm run app:scaffold — app "${slug}" (configs/app.blueprint.json)\n` +
    `# Do not edit by hand; re-run scaffold after blueprint changes.\n` +
    `#\n` +
    `# Infra (Redis / Postgres): docker compose -f docker/compose.yaml --profile infra up -d\n\n`;

  if (!shouldEmitDockerInfra(bp)) {
    return `${header}services: {}\n`;
  }

  const chunks: string[] = [];

  if (bp.redis !== "none") {
    chunks.push(`  redis:
    profiles: [infra]
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
`);
  }

  if (bp.database === "postgres") {
    const vol = postgresVolumeName(slug);
    chunks.push(`  postgres:
    profiles: [infra]
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - ${vol}:/var/lib/postgresql/data
`);
  }

  if (chunks.length === 0) {
    return `${header}services: {}\n`;
  }

  let body = `${header}services:\n${chunks.join("\n")}`;
  if (bp.database === "postgres") {
    body += `\nvolumes:\n  ${postgresVolumeName(slug)}:\n`;
  }
  return `${body}\n`;
}

function blueprintNodeEnvLines(bp: SaaSAppBlueprint): string[] {
  if (!shouldEmitDockerInfra(bp)) return [];
  const lines: string[] = [];
  if (bp.redis !== "none") {
    lines.push("      REDIS_URL: redis://redis:6379");
  }
  if (bp.database === "postgres") {
    lines.push("      DATABASE_URL: postgres://app:app@postgres:5432/app");
  }
  return lines;
}

/** Replace lines between BLUEPRINT_NODE_ENV markers under node.environment */
export async function patchComposeNodeEnvironment(
  composeMainPath: string,
  bp: SaaSAppBlueprint,
  dryRun: boolean,
): Promise<void> {
  const raw = await fs.readFile(composeMainPath, "utf8");
  const si = raw.indexOf(NODE_ENV_START);
  const ei = raw.indexOf(NODE_ENV_END);
  if (si === -1 || ei === -1 || ei < si) {
    console.warn(
      `[scaffold] Missing BLUEPRINT_NODE_ENV markers in ${composeMainPath} — skip env patch.`,
    );
    return;
  }

  const innerLines = blueprintNodeEnvLines(bp);
  const inner = innerLines.length > 0 ? `\n${innerLines.join("\n")}\n` : "\n";

  const next =
    raw.slice(0, si + NODE_ENV_START.length) + inner + raw.slice(ei);

  if (dryRun) {
    console.log(`[dry-run] would patch node env in ${composeMainPath}`);
    return;
  }
  await fs.writeFile(composeMainPath, next, "utf8");
}

export async function writeComposeGenerated(
  outPath: string,
  bp: SaaSAppBlueprint,
  slug: string,
  dryRun: boolean,
): Promise<void> {
  const body = dockerComposeGeneratedContents(bp, slug);
  if (dryRun) {
    console.log(`[dry-run] would write ${outPath}`);
    return;
  }
  await fs.writeFile(outPath, body, "utf8");
}
