name: App todoapp CI

on:
  push:
    paths:
      - "apps/todoapp-instance/**"
      - "apps/todoapp-api/**"
      - "package-lock.json"
  pull_request:
    paths:
      - "apps/todoapp-instance/**"
      - "apps/todoapp-api/**"
      - "package-lock.json"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm
      - run: npm ci
      - name: API test
        run: npm run test -w todoapp-api
      - name: Web build
        run: npm run build -w todoapp-instance
